# Generated by Django 4.1.7 on 2023-05-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('co_autor', models.CharField(blank=True, max_length=50, null=True)),
                ('data_cadastro', models.DateField()),
                ('emprestado', models.BooleanField(blank=True, default=False, null=True)),
                ('nome_emprestado', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
